name: oraculum
channels:
  - conda-forge
  - pytorch
dependencies:
  - ebooklib
  - bs4
  - transformers
  - ca-certificates
  - openssl
  - sentencepiece
  - certifi
  - protobuf
  - pytorch
  - torchvision
  - torchaudio
  - python-dotenv
  - google-cloud-language
  - jupyter
  - openai
  - langchain-text-splitters
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - python-jose
  - psycopg2
  - passlib
  - alembic
  - rq
  - pip:
      - weaviate-client
