name: oraculum
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12.3
  - ebooklib
  - bs4
  - ca-certificates
  - openssl
  - certifi
  - protobuf
  - python-dotenv
  - jupyter
  - openai
  - langchain
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - python-jose
  - psycopg2
  - passlib
  - alembic
  - networkx
  - pip:
    - langfuse