name: oraculum
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12.3  # or any version you want to use
  - ebooklib
  - bs4
  - transformers
  - ca-certificates
  - openssl
  - certifi
  - protobuf
  - python-dotenv
  - jupyter
  - openai
  - langchain
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - python-jose
  - psycopg2
  - passlib
  - alembic
  - rq
  - pip:
    - langfuse