name: oraculum
channels:
  - pytorch
  - conda-forge
dependencies:
  - ebooklib
  - bs4
  - transformers
  - ca-certificates
  - openssl
  - sentencepiece
  - certifi
  - protobuf
  - pytorch
  - torchvision
  - torchaudio
  - python-dotenv
  - google-cloud-language
  - jupyter
  - openai
  - langchain-text-splitters
