"""removed user foreign key in TextPart

Revision ID: 06eb700d310a
Revises: aa27df700815
Create Date: 2024-08-28 08:00:13.915045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06eb700d310a'
down_revision: Union[str, None] = 'aa27df700815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_parts_user_id_fkey', 'book_parts', type_='foreignkey')
    op.drop_column('book_parts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_parts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('book_parts_user_id_fkey', 'book_parts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
