"""add sibling_index in text_part

Revision ID: 2dc121d28b98
Revises: 06eb700d310a
Create Date: 2024-08-28 08:30:35.172615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc121d28b98'
down_revision: Union[str, None] = '06eb700d310a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_parts', sa.Column('sibling_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_parts', 'sibling_index')
    # ### end Alembic commands ###
