"""add book file hashing

Revision ID: 6dcaa4463eaf
Revises: ef9bfb4a2261
Create Date: 2024-08-02 15:36:51.708415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcaa4463eaf'
down_revision: Union[str, None] = 'ef9bfb4a2261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_files', sa.Column('data_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_files', 'data_hash')
    # ### end Alembic commands ###
