"""nullable siblings

Revision ID: 6e1c728aed99
Revises: a6f9822d382c
Create Date: 2024-09-30 17:18:54.530999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1c728aed99'
down_revision: Union[str, None] = 'a6f9822d382c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base_entries', 'sibling_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('knowledge_base_entries', 'sibling_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base_entries', 'sibling_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('knowledge_base_entries', 'sibling_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
