"""add is_entity_extracted in book parts and sibling logic in kb entries

Revision ID: 8b55c5aaf8be
Revises: da21f26e1a2b
Create Date: 2024-09-04 15:52:39.562166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b55c5aaf8be'
down_revision: Union[str, None] = 'da21f26e1a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base_entries', sa.Column('sibling_index', sa.Integer(), nullable=False))
    op.add_column('knowledge_base_entries', sa.Column('sibling_total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base_entries', 'sibling_total')
    op.drop_column('knowledge_base_entries', 'sibling_index')
    # ### end Alembic commands ###
