"""add base64 cover image

Revision ID: b16d40e12e61
Revises: 6dcaa4463eaf
Create Date: 2024-08-05 16:49:20.100152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16d40e12e61'
down_revision: Union[str, None] = '6dcaa4463eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_files', sa.Column('cover_image_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_files', 'cover_image_base64')
    # ### end Alembic commands ###
