"""table init

Revision ID: da21f26e1a2b
Revises: 
Create Date: 2024-09-04 13:10:13.899449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da21f26e1a2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('role', sa.String(), server_default='user', nullable=False),
                    sa.Column('balance', sa.Float(), server_default='0', nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('book_files',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('upload_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('file_type', sa.Enum('epub', 'kindle', 'mobi', 'txt', 'rtf', name='filetype'), nullable=False),
                    sa.Column('original_file_name', sa.String(), nullable=False),
                    sa.Column('file_size', sa.Integer(), nullable=False),
                    sa.Column('file_data', postgresql.BYTEA(), nullable=False),
                    sa.Column('author', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('data_hash', sa.String(), nullable=False),
                    sa.Column('cover_image_base64', sa.String(), nullable=True),
                    sa.Column('is_parsed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('book_parts',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('parent_id', sa.UUID(), nullable=True),
                    sa.Column('toc_id', sa.String(), nullable=False),
                    sa.Column('label', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('sibling_index', sa.Integer(), nullable=False),
                    sa.Column('is_story_part', sa.Boolean(), server_default=sa.text('true'), nullable=False),
                    sa.Column('is_entity_extracted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['book_id'], ['book_files.id'], ),
                    sa.ForeignKeyConstraint(['parent_id'], ['book_parts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('knowledge_base_entries',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('book_part_id', sa.UUID(), nullable=False),
                    sa.Column('entity_name', sa.String(), nullable=False),
                    sa.Column('alternative_names', sa.String(), nullable=True),
                    sa.Column('referenced_entity_name', sa.String(), nullable=True),
                    sa.Column('category', sa.String(), nullable=False),
                    sa.Column('fact', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['book_id'], ['book_files.id'], ),
                    sa.ForeignKeyConstraint(['book_part_id'], ['book_parts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base_entries')
    op.drop_table('book_parts')
    op.drop_table('book_files')
    op.drop_table('users')
    # ### end Alembic commands ###
