"""create books table

Revision ID: ef9bfb4a2261
Revises: 6ed7bf656555
Create Date: 2024-07-24 12:40:19.383915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef9bfb4a2261'
down_revision: Union[str, None] = '6ed7bf656555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_files',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('upload_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('file_type', sa.Enum('epub', 'kindle', 'mobi', 'txt', 'rtf', name='filetype'), nullable=False),
                    sa.Column('original_file_name', sa.String(), nullable=False),
                    sa.Column('file_size', sa.Integer(), nullable=False),
                    sa.Column('file_data', postgresql.BYTEA(), nullable=False),
                    sa.Column('author', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_files')
    # ### end Alembic commands ###
