"""book entity extraction start time

Revision ID: f8b3da9280b7
Revises: 8b55c5aaf8be
Create Date: 2024-09-19 16:58:53.927839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8b3da9280b7'
down_revision: Union[str, None] = '8b55c5aaf8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_files', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('book_files', sa.Column('extraction_start_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('book_files', 'upload_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_files', sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('book_files', 'extraction_start_time')
    op.drop_column('book_files', 'created_at')
    # ### end Alembic commands ###
